# Generated by Django 5.0.1 on 2024-02-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("timetable_html", models.TextField()),
                ("remedial_html", models.TextField(null=True)),
                ("timetable_info_json", models.JSONField()),
                ("remedial_info_json", models.JSONField(null=True)),
                ("occupied_classrooms", models.TextField()),
            ],
        ),
    ]
