# Generated by Django 5.0.1 on 2024-01-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "name",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("timetable_html", models.TextField()),
                ("occupied_classrooms", models.TextField()),
            ],
        ),
    ]
